<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
                ['name' => 'Afghanistan', 'code' => 'AF', 'flag' => '🇦🇫', 'phone_code' => '+93'],
                ['name' => 'Albania', 'code' => 'AL', 'flag' => '🇦🇱', 'phone_code' => '+355'],
                ['name' => 'Algeria', 'code' => 'DZ', 'flag' => '🇩🇿', 'phone_code' => '+213'],
                ['name' => 'Andorra', 'code' => 'AD', 'flag' => '🇦🇩', 'phone_code' => '+376'],
                ['name' => 'Angola', 'code' => 'AO', 'flag' => '🇦🇴', 'phone_code' => '+244'],
                ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'flag' => '🇦🇬', 'phone_code' => '+1-268'],
                ['name' => 'Argentina', 'code' => 'AR', 'flag' => '🇦🇷', 'phone_code' => '+54'],
                ['name' => 'Armenia', 'code' => 'AM', 'flag' => '🇦🇲', 'phone_code' => '+374'],
                ['name' => 'Australia', 'code' => 'AU', 'flag' => '🇦🇺', 'phone_code' => '+61'],
                ['name' => 'Austria', 'code' => 'AT', 'flag' => '🇦🇹', 'phone_code' => '+43'],
                ['name' => 'Azerbaijan', 'code' => 'AZ', 'flag' => '🇦🇿', 'phone_code' => '+994'],
                ['name' => 'Bahamas', 'code' => 'BS', 'flag' => '🇧🇸', 'phone_code' => '+1-242'],
                ['name' => 'Bahrain', 'code' => 'BH', 'flag' => '🇧🇭', 'phone_code' => '+973'],
                ['name' => 'Bangladesh', 'code' => 'BD', 'flag' => '🇧🇩', 'phone_code' => '+880'],
                ['name' => 'Barbados', 'code' => 'BB', 'flag' => '🇧🇧', 'phone_code' => '+1-246'],
                ['name' => 'Belarus', 'code' => 'BY', 'flag' => '🇧🇾', 'phone_code' => '+375'],
                ['name' => 'Belgium', 'code' => 'BE', 'flag' => '🇧🇪', 'phone_code' => '+32'],
                ['name' => 'Belize', 'code' => 'BZ', 'flag' => '🇧🇿', 'phone_code' => '+501'],
                ['name' => 'Benin', 'code' => 'BJ', 'flag' => '🇧🇯', 'phone_code' => '+229'],
                ['name' => 'Bhutan', 'code' => 'BT', 'flag' => '🇧🇹', 'phone_code' => '+975'],
                ['name' => 'Bolivia', 'code' => 'BO', 'flag' => '🇧🇴', 'phone_code' => '+591'],
                ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'flag' => '🇧🇦', 'phone_code' => '+387'],
                ['name' => 'Botswana', 'code' => 'BW', 'flag' => '🇧🇼', 'phone_code' => '+267'],
                ['name' => 'Brazil', 'code' => 'BR', 'flag' => '🇧🇷', 'phone_code' => '+55'],
                ['name' => 'Brunei Darussalam', 'code' => 'BN', 'flag' => '🇧🇳', 'phone_code' => '+673'],
                ['name' => 'Bulgaria', 'code' => 'BG', 'flag' => '🇧🇬', 'phone_code' => '+359'],
                ['name' => 'Burkina Faso', 'code' => 'BF', 'flag' => '🇧🇫', 'phone_code' => '+226'],
                ['name' => 'Burundi', 'code' => 'BI', 'flag' => '🇧🇮', 'phone_code' => '+257'],
                ['name' => 'Cabo Verde', 'code' => 'CV', 'flag' => '🇨🇻', 'phone_code' => '+238'],
                ['name' => 'Cambodia', 'code' => 'KH', 'flag' => '🇰🇭', 'phone_code' => '+855'],
                ['name' => 'Cameroon', 'code' => 'CM', 'flag' => '🇨🇲', 'phone_code' => '+237'],
                ['name' => 'Canada', 'code' => 'CA', 'flag' => '🇨🇦', 'phone_code' => '+1'],
                ['name' => 'Central African Republic', 'code' => 'CF', 'flag' => '🇨🇫', 'phone_code' => '+236'],
                ['name' => 'Chad', 'code' => 'TD', 'flag' => '🇹🇩', 'phone_code' => '+235'],
                ['name' => 'Chile', 'code' => 'CL', 'flag' => '🇨🇱', 'phone_code' => '+56'],
                ['name' => 'China', 'code' => 'CN', 'flag' => '🇨🇳', 'phone_code' => '+86'],
                ['name' => 'Colombia', 'code' => 'CO', 'flag' => '🇨🇴', 'phone_code' => '+57'],
                ['name' => 'Comoros', 'code' => 'KM', 'flag' => '🇰🇲', 'phone_code' => '+269'],
                ['name' => 'Congo (Congo-Brazzaville)', 'code' => 'CG', 'flag' => '🇨🇬', 'phone_code' => '+242'],
                ['name' => 'Congo (Democratic Republic)', 'code' => 'CD', 'flag' => '🇨🇩', 'phone_code' => '+243'],
                ['name' => 'Costa Rica', 'code' => 'CR', 'flag' => '🇨🇷', 'phone_code' => '+506'],
                ['name' => 'Croatia', 'code' => 'HR', 'flag' => '🇭🇷', 'phone_code' => '+385'],
                ['name' => 'Cuba', 'code' => 'CU', 'flag' => '🇨🇺', 'phone_code' => '+53'],
                ['name' => 'Cyprus', 'code' => 'CY', 'flag' => '🇨🇾', 'phone_code' => '+357'],
                ['name' => 'Czechia (Czech Republic)', 'code' => 'CZ', 'flag' => '🇨🇿', 'phone_code' => '+420'],
                ['name' => 'Denmark', 'code' => 'DK', 'flag' => '🇩🇰', 'phone_code' => '+45'],
                ['name' => 'Djibouti', 'code' => 'DJ', 'flag' => '🇩🇯', 'phone_code' => '+253'],
                ['name' => 'Dominica', 'code' => 'DM', 'flag' => '🇩🇲', 'phone_code' => '+1-767'],
                ['name' => 'Dominican Republic', 'code' => 'DO', 'flag' => '🇩🇴', 'phone_code' => '+1-809'],
                ['name' => 'Ecuador', 'code' => 'EC', 'flag' => '🇪🇨', 'phone_code' => '+593'],
                ['name' => 'Egypt', 'code' => 'EG', 'flag' => '🇪🇬', 'phone_code' => '+20'],
                ['name' => 'El Salvador', 'code' => 'SV', 'flag' => '🇸🇻', 'phone_code' => '+503'],
                ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'flag' => '🇬🇶', 'phone_code' => '+240'],
                ['name' => 'Eritrea', 'code' => 'ER', 'flag' => '🇪🇷', 'phone_code' => '+291'],
                ['name' => 'Estonia', 'code' => 'EE', 'flag' => '🇪🇪', 'phone_code' => '+372'],
                ['name' => 'Eswatini (fmr. "Swaziland")', 'code' => 'SZ', 'flag' => '🇸🇿', 'phone_code' => '+268'],
                ['name' => 'Ethiopia', 'code' => 'ET', 'flag' => '🇪🇹', 'phone_code' => '+251'],
                ['name' => 'Fiji', 'code' => 'FJ', 'flag' => '🇫🇯', 'phone_code' => '+679'],
                ['name' => 'Finland', 'code' => 'FI', 'flag' => '🇫🇮', 'phone_code' => '+358'],
                ['name' => 'France', 'code' => 'FR', 'flag' => '🇫🇷', 'phone_code' => '+33'],
                ['name' => 'Gabon', 'code' => 'GA', 'flag' => '🇬🇦', 'phone_code' => '+241'],
                ['name' => 'Gambia', 'code' => 'GM', 'flag' => '🇬🇲', 'phone_code' => '+220'],
                ['name' => 'Georgia', 'code' => 'GE', 'flag' => '🇬🇪', 'phone_code' => '+995'],
                ['name' => 'Germany', 'code' => 'DE', 'flag' => '🇩🇪', 'phone_code' => '+49'],
                ['name' => 'Ghana', 'code' => 'GH', 'flag' => '🇬🇭', 'phone_code' => '+233'],
                ['name' => 'Greece', 'code' => 'GR', 'flag' => '🇬🇷', 'phone_code' => '+30'],
                ['name' => 'Grenada', 'code' => 'GD', 'flag' => '🇬🇩', 'phone_code' => '+1-473'],
                ['name' => 'Guatemala', 'code' => 'GT', 'flag' => '🇬🇹', 'phone_code' => '+502'],
                ['name' => 'Guinea', 'code' => 'GN', 'flag' => '🇬🇳', 'phone_code' => '+224'],
                ['name' => 'Guinea-Bissau', 'code' => 'GW', 'flag' => '🇬🇼', 'phone_code' => '+245'],
                ['name' => 'Guyana', 'code' => 'GY', 'flag' => '🇬🇾', 'phone_code' => '+592'],
                ['name' => 'Haiti', 'code' => 'HT', 'flag' => '🇭🇹', 'phone_code' => '+509'],
                ['name' => 'Honduras', 'code' => 'HN', 'flag' => '🇭🇳', 'phone_code' => '+504'],
                ['name' => 'Hungary', 'code' => 'HU', 'flag' => '🇭🇺', 'phone_code' => '+36'],
                ['name' => 'Iceland', 'code' => 'IS', 'flag' => '🇮🇸', 'phone_code' => '+354'],
                ['name' => 'India', 'code' => 'IN', 'flag' => '🇮🇳', 'phone_code' => '+91'],
                ['name' => 'Indonesia', 'code' => 'ID', 'flag' => '🇮🇩', 'phone_code' => '+62'],
                ['name' => 'Iran', 'code' => 'IR', 'flag' => '🇮🇷', 'phone_code' => '+98'],
                ['name' => 'Iraq', 'code' => 'IQ', 'flag' => '🇮🇶', 'phone_code' => '+964'],
                ['name' => 'Ireland', 'code' => 'IE', 'flag' => '🇮🇪', 'phone_code' => '+353'],
                ['name' => 'Israel', 'code' => 'IL', 'flag' => '🇮🇱', 'phone_code' => '+972'],
                ['name' => 'Italy', 'code' => 'IT', 'flag' => '🇮🇹', 'phone_code' => '+39'],
                ['name' => 'Jamaica', 'code' => 'JM', 'flag' => '🇯🇲', 'phone_code' => '+1-876'],
                ['name' => 'Japan', 'code' => 'JP', 'flag' => '🇯🇵', 'phone_code' => '+81'],
                ['name' => 'Jordan', 'code' => 'JO', 'flag' => '🇯🇴', 'phone_code' => '+962'],
                ['name' => 'Kazakhstan', 'code' => 'KZ', 'flag' => '🇰🇿', 'phone_code' => '+7'],
                ['name' => 'Kenya', 'code' => 'KE', 'flag' => '🇰🇪', 'phone_code' => '+254'],
                ['name' => 'Kiribati', 'code' => 'KI', 'flag' => '🇰🇮', 'phone_code' => '+686'],
                ['name' => 'Kuwait', 'code' => 'KW', 'flag' => '🇰🇼', 'phone_code' => '+965'],
                ['name' => 'Kyrgyzstan', 'code' => 'KG', 'flag' => '🇰🇬', 'phone_code' => '+996'],
                ['name' => 'Laos', 'code' => 'LA', 'flag' => '🇱🇦', 'phone_code' => '+856'],
                ['name' => 'Latvia', 'code' => 'LV', 'flag' => '🇱🇻', 'phone_code' => '+371'],
                ['name' => 'Lebanon', 'code' => 'LB', 'flag' => '🇱🇧', 'phone_code' => '+961'],
                ['name' => 'Lesotho', 'code' => 'LS', 'flag' => '🇱🇸', 'phone_code' => '+266'],
                ['name' => 'Liberia', 'code' => 'LR', 'flag' => '🇱🇷', 'phone_code' => '+231'],
                ['name' => 'Libya', 'code' => 'LY', 'flag' => '🇱🇾', 'phone_code' => '+218'],
                ['name' => 'Liechtenstein', 'code' => 'LI', 'flag' => '🇱🇮', 'phone_code' => '+423'],
                ['name' => 'Lithuania', 'code' => 'LT', 'flag' => '🇱🇹', 'phone_code' => '+370'],
                ['name' => 'Luxembourg', 'code' => 'LU', 'flag' => '🇱🇺', 'phone_code' => '+352'],
                ['name' => 'Madagascar', 'code' => 'MG', 'flag' => '🇲🇬', 'phone_code' => '+261'],
                ['name' => 'Malawi', 'code' => 'MW', 'flag' => '🇲🇼', 'phone_code' => '+265'],
                ['name' => 'Malaysia', 'code' => 'MY', 'flag' => '🇲🇾', 'phone_code' => '+60'],
                ['name' => 'Maldives', 'code' => 'MV', 'flag' => '🇲🇻', 'phone_code' => '+960'],
                ['name' => 'Mali', 'code' => 'ML', 'flag' => '🇲🇱', 'phone_code' => '+223'],
                ['name' => 'Malta', 'code' => 'MT', 'flag' => '🇲🇹', 'phone_code' => '+356'],
                ['name' => 'Marshall Islands', 'code' => 'MH', 'flag' => '🇲🇭', 'phone_code' => '+692'],
                ['name' => 'Mauritania', 'code' => 'MR', 'flag' => '🇲🇷', 'phone_code' => '+222'],
                ['name' => 'Mauritius', 'code' => 'MU', 'flag' => '🇲🇺', 'phone_code' => '+230'],
                ['name' => 'Mexico', 'code' => 'MX', 'flag' => '🇲🇽', 'phone_code' => '+52'],
                ['name' => 'Micronesia', 'code' => 'FM', 'flag' => '🇫🇲', 'phone_code' => '+691'],
                ['name' => 'Moldova', 'code' => 'MD', 'flag' => '🇲🇩', 'phone_code' => '+373'],
                ['name' => 'Monaco', 'code' => 'MC', 'flag' => '🇲🇨', 'phone_code' => '+377'],
                ['name' => 'Mongolia', 'code' => 'MN', 'flag' => '🇲🇳', 'phone_code' => '+976'],
                ['name' => 'Montenegro', 'code' => 'ME', 'flag' => '🇲🇪', 'phone_code' => '+382'],
                ['name' => 'Morocco', 'code' => 'MA', 'flag' => '🇲🇦', 'phone_code' => '+212'],
                ['name' => 'Mozambique', 'code' => 'MZ', 'flag' => '🇲🇿', 'phone_code' => '+258'],
                ['name' => 'Myanmar', 'code' => 'MM', 'flag' => '🇲🇲', 'phone_code' => '+95'],
                ['name' => 'Namibia', 'code' => 'NA', 'flag' => '🇳🇦', 'phone_code' => '+264'],
                ['name' => 'Nauru', 'code' => 'NR', 'flag' => '🇳🇷', 'phone_code' => '+674'],
                ['name' => 'Nepal', 'code' => 'NP', 'flag' => '🇳🇵', 'phone_code' => '+977'],
                ['name' => 'Netherlands', 'code' => 'NL', 'flag' => '🇳🇱', 'phone_code' => '+31'],
                ['name' => 'New Zealand', 'code' => 'NZ', 'flag' => '🇳🇿', 'phone_code' => '+64'],
                ['name' => 'Nicaragua', 'code' => 'NI', 'flag' => '🇳🇮', 'phone_code' => '+505'],
                ['name' => 'Niger', 'code' => 'NE', 'flag' => '🇳🇪', 'phone_code' => '+227'],
                ['name' => 'Nigeria', 'code' => 'NG', 'flag' => '🇳🇬', 'phone_code' => '+234'],
                ['name' => 'North Korea', 'code' => 'KP', 'flag' => '🇰🇵', 'phone_code' => '+850'],
                ['name' => 'North Macedonia', 'code' => 'MK', 'flag' => '🇲🇰', 'phone_code' => '+389'],
                ['name' => 'Norway', 'code' => 'NO', 'flag' => '🇳🇴', 'phone_code' => '+47'],
                ['name' => 'Oman', 'code' => 'OM', 'flag' => '🇴🇲', 'phone_code' => '+968'],
                ['name' => 'Pakistan', 'code' => 'PK', 'flag' => '🇵🇰', 'phone_code' => '+92'],
                ['name' => 'Palau', 'code' => 'PW', 'flag' => '🇵🇼', 'phone_code' => '+680'],
                ['name' => 'Palestine', 'code' => 'PS', 'flag' => '🇵🇸', 'phone_code' => '+970'],
                ['name' => 'Panama', 'code' => 'PA', 'flag' => '🇵🇦', 'phone_code' => '+507'],
                ['name' => 'Papua New Guinea', 'code' => 'PG', 'flag' => '🇵🇬', 'phone_code' => '+675'],
                ['name' => 'Paraguay', 'code' => 'PY', 'flag' => '🇵🇾', 'phone_code' => '+595'],
                ['name' => 'Peru', 'code' => 'PE', 'flag' => '🇵🇪', 'phone_code' => '+51'],
                ['name' => 'Philippines', 'code' => 'PH', 'flag' => '🇵🇭', 'phone_code' => '+63'],
                ['name' => 'Poland', 'code' => 'PL', 'flag' => '🇵🇱', 'phone_code' => '+48'],
                ['name' => 'Portugal', 'code' => 'PT', 'flag' => '🇵🇹', 'phone_code' => '+351'],
                ['name' => 'Qatar', 'code' => 'QA', 'flag' => '🇶🇦', 'phone_code' => '+974'],
                ['name' => 'Romania', 'code' => 'RO', 'flag' => '🇷🇴', 'phone_code' => '+40'],
                ['name' => 'Russia', 'code' => 'RU', 'flag' => '🇷🇺', 'phone_code' => '+7'],
                ['name' => 'Rwanda', 'code' => 'RW', 'flag' => '🇷🇼', 'phone_code' => '+250'],
                ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'flag' => '🇰🇳', 'phone_code' => '+1-869'],
                ['name' => 'Saint Lucia', 'code' => 'LC', 'flag' => '🇱🇨', 'phone_code' => '+1-758'],
                ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'flag' => '🇻🇨', 'phone_code' => '+1-784'],
                ['name' => 'Samoa', 'code' => 'WS', 'flag' => '🇼🇸', 'phone_code' => '+685'],
                ['name' => 'San Marino', 'code' => 'SM', 'flag' => '🇸🇲', 'phone_code' => '+378'],
                ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'flag' => '🇸🇹', 'phone_code' => '+239'],
                ['name' => 'Saudi Arabia', 'code' => 'SA', 'flag' => '🇸🇦', 'phone_code' => '+966'],
                ['name' => 'Senegal', 'code' => 'SN', 'flag' => '🇸🇳', 'phone_code' => '+221'],
                ['name' => 'Serbia', 'code' => 'RS', 'flag' => '🇷🇸', 'phone_code' => '+381'],
                ['name' => 'Seychelles', 'code' => 'SC', 'flag' => '🇸🇨', 'phone_code' => '+248'],
                ['name' => 'Sierra Leone', 'code' => 'SL', 'flag' => '🇸🇱', 'phone_code' => '+232'],
                ['name' => 'Singapore', 'code' => 'SG', 'flag' => '🇸🇬', 'phone_code' => '+65'],
                ['name' => 'Slovakia', 'code' => 'SK', 'flag' => '🇸🇰', 'phone_code' => '+421'],
                ['name' => 'Slovenia', 'code' => 'SI', 'flag' => '🇸🇮', 'phone_code' => '+386'],
                ['name' => 'Solomon Islands', 'code' => 'SB', 'flag' => '🇸🇧', 'phone_code' => '+677'],
                ['name' => 'Somalia', 'code' => 'SO', 'flag' => '🇸🇴', 'phone_code' => '+252'],
                ['name' => 'South Africa', 'code' => 'ZA', 'flag' => '🇿🇦', 'phone_code' => '+27'],
                ['name' => 'South Korea', 'code' => 'KR', 'flag' => '🇰🇷', 'phone_code' => '+82'],
                ['name' => 'South Sudan', 'code' => 'SS', 'flag' => '🇸🇸', 'phone_code' => '+211'],
                ['name' => 'Spain', 'code' => 'ES', 'flag' => '🇪🇸', 'phone_code' => '+34'],
                ['name' => 'Sri Lanka', 'code' => 'LK', 'flag' => '🇱🇰', 'phone_code' => '+94'],
                ['name' => 'Sudan', 'code' => 'SD', 'flag' => '🇸🇩', 'phone_code' => '+249'],
                ['name' => 'Suriname', 'code' => 'SR', 'flag' => '🇸🇷', 'phone_code' => '+597'],
                ['name' => 'Sweden', 'code' => 'SE', 'flag' => '🇸🇪', 'phone_code' => '+46'],
                ['name' => 'Switzerland', 'code' => 'CH', 'flag' => '🇨🇭', 'phone_code' => '+41'],
                ['name' => 'Syria', 'code' => 'SY', 'flag' => '🇸🇾', 'phone_code' => '+963'],
                ['name' => 'Taiwan', 'code' => 'TW', 'flag' => '🇹🇼', 'phone_code' => '+886'],
                ['name' => 'Tajikistan', 'code' => 'TJ', 'flag' => '🇹🇯', 'phone_code' => '+992'],
                ['name' => 'Tanzania', 'code' => 'TZ', 'flag' => '🇹🇿', 'phone_code' => '+255'],
                ['name' => 'Thailand', 'code' => 'TH', 'flag' => '🇹🇭', 'phone_code' => '+66'],
                ['name' => 'Timor-Leste', 'code' => 'TL', 'flag' => '🇹🇱', 'phone_code' => '+670'],
                ['name' => 'Togo', 'code' => 'TG', 'flag' => '🇹🇬', 'phone_code' => '+228'],
                ['name' => 'Tonga', 'code' => 'TO', 'flag' => '🇹🇴', 'phone_code' => '+676'],
                ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'flag' => '🇹🇹', 'phone_code' => '+1-868'],
                ['name' => 'Tunisia', 'code' => 'TN', 'flag' => '🇹🇳', 'phone_code' => '+216'],
                ['name' => 'Turkey', 'code' => 'TR', 'flag' => '🇹🇷', 'phone_code' => '+90'],
                ['name' => 'Turkmenistan', 'code' => 'TM', 'flag' => '🇹🇲', 'phone_code' => '+993'],
                ['name' => 'Tuvalu', 'code' => 'TV', 'flag' => '🇹🇻', 'phone_code' => '+688'],
                ['name' => 'Uganda', 'code' => 'UG', 'flag' => '🇺🇬', 'phone_code' => '+256'],
                ['name' => 'Ukraine', 'code' => 'UA', 'flag' => '🇺🇦', 'phone_code' => '+380'],
                ['name' => 'United Arab Emirates', 'code' => 'AE', 'flag' => '🇦🇪', 'phone_code' => '+971'],
                ['name' => 'United Kingdom', 'code' => 'GB', 'flag' => '🇬🇧', 'phone_code' => '+44'],
                ['name' => 'United States', 'code' => 'US', 'flag' => '🇺🇸', 'phone_code' => '+1'],
                ['name' => 'Uruguay', 'code' => 'UY', 'flag' => '🇺🇾', 'phone_code' => '+598'],
                ['name' => 'Uzbekistan', 'code' => 'UZ', 'flag' => '🇺🇿', 'phone_code' => '+998'],
                ['name' => 'Vanuatu', 'code' => 'VU', 'flag' => '🇻🇺', 'phone_code' => '+678'],
                ['name' => 'Vatican City', 'code' => 'VA', 'flag' => '🇻🇦', 'phone_code' => '+379'],
                ['name' => 'Venezuela', 'code' => 'VE', 'flag' => '🇻🇪', 'phone_code' => '+58'],
                ['name' => 'Vietnam', 'code' => 'VN', 'flag' => '🇻🇳', 'phone_code' => '+84'],
                ['name' => 'Yemen', 'code' => 'YE', 'flag' => '🇾🇪', 'phone_code' => '+967'],
                ['name' => 'Zambia', 'code' => 'ZM', 'flag' => '🇿🇲', 'phone_code' => '+260'],
                ['name' => 'Zimbabwe', 'code' => 'ZW', 'flag' => '🇿🇼', 'phone_code' => '+263'],
        ]);
    }
}
